media:
  input: assets/img/blog
  output: /assets/img/blog
  rename: safe
  categories: [image]

content:
  - name: posts
    label: مطالب وبلاگ
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{address}.md"
    fields:
      - name: title
        label: عنوان
        type: string
      - name: address
        label: آدرس انگلیسی (مثلاً my-first-post)
        type: string
      - name: description
        label: توضیح کوتاه
        type: text
      - name: image
        label: کاور
        type: image
      - name: body
        label: متن مطلب
        type: rich-text
